name: Build and push :master image

permissions:
  contents: read

on:
  push:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2
      - name: check format
        run: make check_format

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@27d0a4f181a40b142cce983c5393082c365d1480 # v1.2.0

      - name: Set up Docker buildx
        id: buildx
        uses: docker/setup-buildx-action@2b51285047da1547ffb1b2203d8be4c0af6b1f20 # v3.2.0

      - name: Extract PR number
        run: echo "PR_NUMBER=${{ github.event.pull_request.number }}" >> $GITHUB_ENV
      - name: dump
        run: cat $GITHUB_ENV
      # - name: build and push docker image
      #   run: |
      #     echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      #     VERSION=master make docker_multiarch_push     # Push image tagged with "master"
      #     make docker_multiarch_push                    # Push image tagged with git sha
      #   env:
      #     DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      #     DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: build and push s docker image
        run: |
          echo "$DOCKER" | docker login -u prabhj --password-stdin
          VERSION=master make docker_multiarch_push_fips     # Push image tagged with "master"
          make docker_multiarch_push_fips                    # Push image tagged with git sha
        env:
          # DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER: ${{ secrets.DOCKER }}         

